### ISSUE TITLE
Broken implementation

### ISSUE THREAD

**Issue by vhermecz** [leegao/pyXLSX#1]
I wanted to open my xlsx file, but got Exception, due to an empty cell, which has no <v .../> node in it. Just fixed it. Afterwards got ValueError, because the cell's value was 251.75

**Comment by vhermecz** [comment]
I cant understand, why would someone upload a half-ready implementation. 
The regcell function is so gloriously broken, you should see it for yourself, maybe post it to DailyWTF.
Shouldt commit a code like this to any public place. Just spent half an hour realizing this is not the lib I want to use.

**Comment by leegao** [comment]
Haha, sorry about the inconvenience. I started this as a sort of a side project to help me "procrastinate." Once my real task was completed, I lost the energy to develop this any further as I had no more interest in doing so and as no one as have used this. 

I'll restart this project if you really do need an xlsx parser, however it may also be beneficial for you to convert your xlsx documents into xls and use pyxlreader. http://pyxlreader.sourceforge.net/

Cheers.

**Comment by leegao** [comment]
Okay, I've done a complete revamp of the project in the last few hours. pyXLSX will now correctly parse text, integers, and floats. I will need to implement some sort of testing framework pending the addition of arbitrary data types (addresses, currency, dates, etc). pyXLSX can also interpolate Excel formula elements, however many of the excel formulas will have to be rewritten in python (you can use the @Workbook.extend decorator, where Workbook is an instance of workbook). The next commit will also feature intercell signaling in order to automate formula updates whenever cells are changed. If I find time, I might also write something to reserialize the manipulated data back into xlsx format.
